### GET hello
GET http://localhost:8888/hello

### GET gw 1
GET http://localhost:8888/gw

### POST user
POST http://localhost:8888/gw/yyrpc/cn.youyou.yyrpc.demo.api.UserService
Content-Type: application/json

{
  "service":"cn.youyou.yyrpc.demo.api.UserService",
  "methodSign":"findById@1_int",
  "args":[100]
}

### POST direct
POST http://localhost:8888/gw/direct/cn.youyou.yyrpc.demo.api.UserService
Content-Type: application/json

{
  "service":"cn.youyou.yyrpc.demo.api.UserService",
  "methodSign":"findById@1_int",
  "args":[100]
}

### POST direct backend
POST http://localhost:8888/gw/direct/cn.youyou.yyrpc.demo.api.UserService?backend=http://localhost:8081/yyrpc
Content-Type: application/json

{
  "service":"cn.youyou.yyrpc.demo.api.UserService",
  "methodSign":"findById@1_int",
  "args":[100]
}